package com.nordokod.scio.constants;

public enum ErrorMessage {
    NETWORK_PHONE,
    NETWORK_FIREABSE,
    AUTH_INVALID_CREDENTIALS,
    AUTH_SEND_EMAIL,
    AUTH_INVALID_USER,
    AUTH_USER_COLLISION,
    AUTH_UNKNOW,
    FIRESTORE_EXCEPTION,
    STORAGE_EXCEPTION,
    FIREBASE_EXCEPTION,
    FACEBOOK_EXCEPTION,
    GOOGLE_EXCEPTION,
    USER_PERMISSION,
    CANCELED_OPERATION,
    INVALID_INTERN_VALUE,
    DATETIME_AFTER,
    DATETIME_BEFORE,
    INVALID_MAIL,
    INVALID_PASSWORD,
    INVALID_USERNAME,
    PASSWORDS_DONT_MATCH,
    EMPTY_FIELD,
    UNKNOW_EXCEPTION;
}