package com.nordokod.scio.old.constants;

import com.nordokod.scio.R;

public enum ErrorMessage {
    NETWORK_PHONE(R.string.NETWORK_PHONE_TITLE,2,R.string.NETWORK_PHONE_MESSAGE),
    NETWORK_FIREABSE(R.string.NETWORK_FIREBASE_TITLE,2,R.string.NETWORK_FIREBASE_MESSAGE),
    AUTH_INVALID_CREDENTIALS(R.string.AUTH_INVALID_CREDENTIALS_TITLE,2,R.string.AUTH_INVALID_CREDENTIALS_MESSAGE),
    AUTH_SEND_EMAIL(R.string.AUTH_SEND_MAIL_TITLE,2,R.string.AUTH_SEND_MAIL_MESSAGE),
    AUTH_INVALID_USER(R.string.AUTH_INVALID_USER_TITLE,2,R.string.AUTH_INVALID_USER_MESSAGE),
    AUTH_USER_COLLISION(R.string.AUTH_USER_COLLISION_TITLE,2,R.string.AUTH_USER_COLLISION_MESSAGE),
    AUTH_UNKNOW(R.string.AUTH_UNKNOW_TITLE,2,R.string.AUTH_UNKNOW_MESSAGE),
    FIRESTORE_EXCEPTION(R.string.FIRESTORE_EXCEPTION_TITLE,2,R.string.FIRESTORE_EXCEPTION_MESSAGE),
    STORAGE_EXCEPTION(R.string.STORAGE_EXCEPTION_TITLE,2,R.string.STORAGE_EXCEPTION_MESSAGE),
    FIREBASE_EXCEPTION(R.string.FIREBASE_EXCEPTION_TITLE,2,R.string.FIREBASE_EXCEPTION_MESSAGE),
    FACEBOOK_EXCEPTION(R.string.FACEBOOK_EXCEPTION_TITLE,2,R.string.FACEBOOK_EXCEPTION_MESSAGE),
    GOOGLE_EXCEPTION(R.string.GOOGLE_EXCEPTION_TITLE,2,R.string.GOOGLE_EXCEPTION_MESSAGE),
    USER_PERMISSION(R.string.USER_PERMISSION_TITLE,1,R.string.USER_PERMISSION_MESSAGE),
    CANCELED_OPERATION(R.string.CANCELED_OPERATION_TITLE,1,R.string.CANCELED_OPERATION_MESSAGE),
    INVALID_INTERN_VALUE(R.string.INVALID_INTERN_VALUE_TITLE,2,R.string.INVALID_INTERN_VALUE_MESSAGE),
    DATETIME_AFTER(R.string.DATETIME_AFTER_TITLE,1,R.string.DATETIME_AFTER_MESSAGE),
    DATETIME_BEFORE(R.string.DATETIME_BEFORE_TITLE,1,R.string.DATETIME_BEFORE_MESSAGE),
    INVALID_MAIL(R.string.INVALID_MAIL_TITLE,1,R.string.INVALID_MAIL_MESSAGE),
    INVALID_PASSWORD(R.string.INVALID_PASSWORD_TITLE,1,R.string.INVALID_PASSWORD_MESSAGE),
    INVALID_USERNAME(R.string.INVALID_USERNAME_TITLE,1,R.string.INVALID_USERNAME_MESSAGE),
    PASSWORDS_DONT_MATCH(R.string.PASSWORDS_DONT_MATCH_TITLE,1,R.string.PASSWORDS_DONT_MATCH_MESSAGE),
    UNKNOWN_EXCEPTION(R.string.UNKNOW_EXCEPTION_TITLE,2,R.string.UNKNOW_EXCEPTION_MESSAGE),
    EMPTY_FIELD(R.string.EMPTY_FIELD_TITLE,1,R.string.EMPTY_FIELD_MESSAGE),
    NO_GUIDES_EXCEPTION(R.string.NO_GUIDES_EXCEPTION_TITLE,1,R.string.NO_GUIDES_EXCEPTION_MESSAGE),
    NOT_ENOUGH_OPTIONS(R.string.NOT_ENOUGH_OPTIONS_TITLE,1,R.string.NOT_ENOUGH_OPTIONS_MESSAGE),
    NOT_CORRECT_OPTION_SELECTED(R.string.NOT_CORRECT_OPTION_SELECTED_TITLE,1,R.string.NOT_CORRECT_OPTION_SELECTED_MESSAGE),
    AUTH_USER_NOT_FOUND(R.string.AUTH_USER_NOT_FOUND_TITLE,2,R.string.AUTH_USER_NOT_FOUND_MESSAGE),
    NO_QUESTIONS_IN_GUIDE(R.string.NO_QUESTIONS_IN_GUIDE_TITLE,2,R.string.NO_QUESTIONS_IN_GUIDE_MESSAGE);

    private int titleCode,kindOfToast,messageCode;

    ErrorMessage(int titleCode, int kindOfToast, int messageCode){
        this.titleCode = titleCode;
        this.kindOfToast = kindOfToast;
        this.messageCode = messageCode;
    }

    public int getTitleCode() { return this.titleCode;}
    public int getMessageCode() { return this.messageCode;}
    public int getKindOfToast() { return kindOfToast; }
}